"""Post-processor engine translating semantic toolpaths into controller-specific G-code.

Supports:
- GRBL / Standard ISO G-code
- Fanuc (standard 3-axis mill with line numbers, safe blocks, canned returns)
- Haas (standard NGC format)
- LinuxCNC (RS274/NGC format)
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Optional
import numpy as np

from ..toolpaths.semantic import MotionSegment, MotionType, Toolpath


@dataclass
class PostResult:
    """The result of post-processing toolpaths into G-code."""
    gcode: str
    line_count: int
    rapid_time_seconds: float
    cut_time_seconds: float
    total_time_seconds: float
    total_rapid_dist_mm: float
    total_cut_dist_mm: float
    tool_changes: list[str]
    work_offset: str = "G54"


class BasePostProcessor:
    """Base modal G-code post-processor."""

    def __init__(
        self,
        precision: int = 3,
        feed_precision: int = 1,
        work_offset: str = "G54",
        default_rapid_feed: float = 3000.0,
    ):
        self.precision = precision
        self.feed_precision = feed_precision
        self.work_offset = work_offset
        self.default_rapid_feed = default_rapid_feed

        # Modal tracking
        self.current_pos = np.array([0.0, 0.0, 0.0])
        self.current_feed: Optional[float] = None
        self.current_spindle: Optional[float] = None
        self.current_motion_mode: Optional[str] = None
        self.spindle_active = False
        self.coolant_active = False
        self.current_tool_id: Optional[str] = None
        self.is_pos_established = False

        # Canned cycle state (G81/G82/G83/G84/G85/G73/G76)
        self.canned_cycle_active = False
        self._cycle_op_id: Optional[str] = None
        self._cycle_r_plane: float = 0.0

        # Safety retract Z (default high; overridden per machine)
        self.retract_z: float = 100.0

        # Cutter compensation state (G41/G42/G40)
        self.comp_active = False
        self.comp_side: Optional[str] = None
        self.hsm_enabled = True
        self.current_hsm_mode: Optional[str] = None

        # Statistics
        self.rapid_dist = 0.0
        self.cut_dist = 0.0
        self.rapid_time = 0.0
        self.cut_time = 0.0
        self.used_tools: list[str] = []

    supported_cycles: set[str] = {"G81", "G82", "G83", "G73", "G84", "G85", "G86", "G76"}

    def supports_cycle(self, cycle_type: str) -> bool:
        return cycle_type in self.supported_cycles

    def _fmt(self, val: float) -> str:
        s = f"{val:.{self.precision}f}"
        return s.rstrip("0").rstrip(".") if "." in s else s

    def _fmt_f(self, val: float) -> str:
        s = f"{val:.{self.feed_precision}f}"
        return s.rstrip("0").rstrip(".") if "." in s else s

    def _fmt_cycle_dwell(self, dwell_seconds: float) -> str:
        """Format dwell P value for canned cycles. Override in subclasses for ms."""
        return f"P{self._fmt(dwell_seconds)}"

    def format_coord(self, axis: str, val: float) -> str:
        return f"{axis}{self._fmt(val)}"

    def start_toolpath(self, tp: Toolpath) -> list[str]:
        """Hook called before toolpath segments. Used for HSM modes (G187/G05.1)."""
        return []

    def header(self, program_name: str = "VEXCAM") -> list[str]:
        return [
            f"; Program: {program_name}",
            "(Generated by VexCAM Engine)",
            f"{self.work_offset} G90 G17 G21 G94 G40 G49 G80",
        ]

    def footer(self) -> list[str]:
        lines = []
        if self.canned_cycle_active:
            lines.append("G80")
            self.canned_cycle_active = False
            self._cycle_op_id = None
        if self.comp_active:
            lines.extend(self.cutter_compensation_off())
            self.comp_active = False
            self.comp_side = None
        if self.coolant_active:
            lines.append("M9")
        if self.spindle_active:
            lines.append("M5")
        lines.append("M30")
        return lines

    def tool_change(self, tool_id: str, tool_num: int = 1,
                    length_offset_h: Optional[int] = None) -> list[str]:
        lines = []
        if self.current_tool_id != tool_id:
            if self.comp_active:
                lines.extend(self.cutter_compensation_off())
                self.comp_active = False
                self.comp_side = None
            if self.spindle_active:
                lines.append("M5")
                self.spindle_active = False
            # Retract Z before tool change for safety
            if self.current_pos[2] < self.retract_z - 1e-6:
                lines.append(f"G0 {self.format_coord('Z', self.retract_z)}")
                self.current_pos[2] = self.retract_z
            lines.append(f"T{tool_num} M6 (Tool: {tool_id})")
            h = length_offset_h if length_offset_h is not None else tool_num
            lines.append(f"G43 H{h}")
            self.current_tool_id = tool_id
            self.is_pos_established = False
            if tool_id not in self.used_tools:
                self.used_tools.append(tool_id)
        return lines

    def cutter_compensation_on(self, side: str = "left", d_register: int = 0) -> list[str]:
        """Enable cutter compensation. side: 'left' (G41) or 'right' (G42).
        d_register: offset register number (matches tool number convention)."""
        g = "G41" if side == "left" else "G42"
        if d_register > 0:
            return [f"{g} D{d_register}"]
        return [f"{g}"]

    def cutter_compensation_off(self) -> list[str]:
        """Cancel cutter compensation."""
        return ["G40"]


    def retract_mode(self, mode: str = "initial_level") -> list[str]:
        """Set canned cycle retract mode. mode: 'initial_level' (G98) or 'r_level' (G99)."""
        if mode == "r_level":
            return ["G99"]
        return ["G98"]

    def process_segment(self, seg: MotionSegment) -> list[str]:
        lines = []
        dist = seg.length()

        # Handle spindle start/stop explicitly
        if seg.motion_type == MotionType.SPINDLE_START:
            if seg.spindle is not None and seg.spindle > 0:
                if seg.spindle != self.current_spindle or not self.spindle_active:
                    lines.append(f"S{int(seg.spindle)} M3")
                    self.current_spindle = seg.spindle
                    self.spindle_active = True
            return lines
        if seg.motion_type == MotionType.SPINDLE_STOP:
            if self.spindle_active:
                lines.append("M5")
                self.spindle_active = False
            return lines

        # Handle spindle speed changes or start (piggybacked on cutting segments)
        if seg.spindle is not None and seg.spindle > 0:
            if seg.spindle != self.current_spindle or not self.spindle_active:
                lines.append(f"S{int(seg.spindle)} M3")
                self.current_spindle = seg.spindle
                self.spindle_active = True

        # Handle tool change
        if seg.motion_type == MotionType.TOOL_CHANGE:
            if self.canned_cycle_active:
                lines.append("G80")
                self.canned_cycle_active = False
                self._cycle_op_id = None
            t_num = 1
            if seg.tool_id and seg.tool_id.startswith("T"):
                try:
                    t_num = int("".join(filter(str.isdigit, seg.tool_id)))
                except ValueError:
                    t_num = 1
            h_offset = seg.metadata.get("length_offset_h")
            lines.extend(self.tool_change(seg.tool_id or "Tool1", t_num, h_offset))
            return lines

        # Handle coolant
        if seg.motion_type == MotionType.COOLANT_ON:
            if not self.coolant_active:
                # M8 = flood coolant (default), M7 = mist, M50 = through-spindle
                coolant_type = seg.metadata.get("coolant_type", "flood") if seg.metadata else "flood"
                if coolant_type == "mist":
                    lines.append("M7")
                elif coolant_type == "through_spindle":
                    lines.append("M50")
                else:
                    lines.append("M8")
                self.coolant_active = True
            return lines
        if seg.motion_type == MotionType.COOLANT_OFF:
            if self.coolant_active:
                lines.append("M9")
                self.coolant_active = False
            return lines

        # Handle Dwell
        if seg.motion_type == MotionType.DWELL:
            lines.append(f"G4 P{self._fmt(seg.dwell_seconds)}")
            self.cut_time += seg.dwell_seconds
            return lines

        # Handle Cutter Compensation (G41/G42/G40)
        comp = seg.metadata.get("cutter_comp") if seg.metadata else None
        if comp:
            action = comp.get("action", "on")
            side = comp.get("side", "left")
            d_reg = comp.get("d_register", 0)
            if action == "on" and not self.comp_active:
                lines.extend(self.cutter_compensation_on(side, d_reg))
                self.comp_active = True
                self.comp_side = side
            elif action == "off" and self.comp_active:
                lines.extend(self.cutter_compensation_off())
                self.comp_active = False
                self.comp_side = None

        # Handle canned cycle detection for drilling

        if seg.metadata.get("canned_cycle") and self.supports_cycle(
                seg.metadata["canned_cycle"].get("type", "G83")):
            cycle = seg.metadata["canned_cycle"]
            cycle_type = cycle.get("type", "G83")
            x = cycle.get("x", seg.end[0])
            y = cycle.get("y", seg.end[1])
            z_r = cycle.get("z_r", seg.start[2])
            z_depth = cycle.get("z_depth", seg.end[2])
            peck = cycle.get("peck", 0.0)
            dwell = cycle.get("dwell", 0.0)
            feed = cycle.get("feed", self.current_feed or 500.0)

            if feed != self.current_feed:
                lines.append(f"F{self._fmt_f(feed)}")
                self.current_feed = feed

            if cycle_type == "G84":
                rpm = seg.spindle or self.current_spindle or 0
                if rpm > 0:
                    lines.append(f"M29 S{int(rpm)}")

            if cycle_type == "G83":
                lines.append(f"G98 G83 {self.format_coord('X', x)} {self.format_coord('Y', y)} "
                           f"{self.format_coord('Z', z_depth)} {self.format_coord('R', z_r)} "
                           f"{self.format_coord('Q', peck)} F{self._fmt_f(feed)}")
            elif cycle_type == "G73":
                lines.append(f"G98 G73 {self.format_coord('X', x)} {self.format_coord('Y', y)} "
                           f"{self.format_coord('Z', z_depth)} {self.format_coord('R', z_r)} "
                           f"{self.format_coord('Q', peck)} F{self._fmt_f(feed)}")
            elif cycle_type == "G81":
                lines.append(f"G98 G81 {self.format_coord('X', x)} {self.format_coord('Y', y)} "
                           f"{self.format_coord('Z', z_depth)} {self.format_coord('R', z_r)} "
                           f"F{self._fmt_f(feed)}")
            elif cycle_type == "G82":
                lines.append(f"G98 G82 {self.format_coord('X', x)} {self.format_coord('Y', y)} "
                           f"{self.format_coord('Z', z_depth)} {self.format_coord('R', z_r)} "
                           f"{self._fmt_cycle_dwell(dwell)} F{self._fmt_f(feed)}")
            elif cycle_type == "G85":
                lines.append(f"G98 G85 {self.format_coord('X', x)} {self.format_coord('Y', y)} "
                           f"{self.format_coord('Z', z_depth)} {self.format_coord('R', z_r)} "
                           f"F{self._fmt_f(feed)}")
            elif cycle_type == "G86":
                lines.append(f"G98 G86 {self.format_coord('X', x)} {self.format_coord('Y', y)} "
                           f"{self.format_coord('Z', z_depth)} {self.format_coord('R', z_r)} "
                           f"F{self._fmt_f(feed)}")
            elif cycle_type == "G76":
                shift = cycle.get("shift", 0.0)
                lines.append(f"G98 G76 {self.format_coord('X', x)} {self.format_coord('Y', y)} "
                           f"{self.format_coord('Z', z_depth)} {self.format_coord('R', z_r)} "
                           f"{self.format_coord('Q', shift)} F{self._fmt_f(feed)}")
            else:
                lines.append(f"G98 {cycle_type} {self.format_coord('X', x)} "
                           f"{self.format_coord('Y', y)} {self.format_coord('Z', z_depth)} "
                           f"{self.format_coord('R', z_r)} F{self._fmt_f(feed)}")

            self.current_pos = np.array([x, y, z_r])
            self.canned_cycle_active = True
            self._cycle_op_id = seg.operation_id
            self._cycle_r_plane = z_r
            self.is_pos_established = True
            return lines

        if self.canned_cycle_active and self._cycle_op_id == seg.operation_id and \
                seg.motion_type in (MotionType.PLUNGE, MotionType.DWELL):
            return lines

        # Handle Rapid motions
        if seg.motion_type in (MotionType.RAPID, MotionType.LINK, MotionType.RETRACT):
            if self.canned_cycle_active and self._cycle_op_id == seg.operation_id and \
                    seg.motion_type is MotionType.RETRACT and \
                    seg.end[2] <= self._cycle_r_plane + 1e-6:
                return lines
            if self.canned_cycle_active:
                lines.append("G80")
                self.canned_cycle_active = False
                self._cycle_op_id = None
            # RETRACT with a feed rate means feed-out (reaming/tapping), emit as G1
            if seg.motion_type is MotionType.RETRACT and seg.feed is not None and seg.feed > 0:
                feed = seg.feed
                self.cut_dist += dist
                self.cut_time += (dist / max(feed, 10.0)) * 60.0
                feed_cmd = ""
                if feed != self.current_feed:
                    feed_cmd = f" F{self._fmt_f(feed)}"
                    self.current_feed = feed
                cmd = self._motion_line("G1", seg.end, extra=feed_cmd)
                if cmd:
                    lines.append(cmd)
                self.current_pos = seg.end.copy()
                return lines
            self.rapid_dist += dist
            self.rapid_time += (dist / max(self.default_rapid_feed, 100.0)) * 60.0
            cmd = self._motion_line("G0", seg.end)
            if cmd:
                lines.append(cmd)
            self.current_pos = seg.end.copy()
            return lines

        # Handle linear cutting moves (HELIX handled separately as G2/G3)
        if seg.motion_type in (MotionType.CUT, MotionType.PLUNGE, MotionType.RAMP,
                               MotionType.ENTRY, MotionType.EXIT):
            if self.canned_cycle_active:
                lines.append("G80")
                self.canned_cycle_active = False
                self._cycle_op_id = None
            feed = seg.feed or self.current_feed or 500.0
            self.cut_dist += dist
            self.cut_time += (dist / max(feed, 10.0)) * 60.0
            feed_cmd = ""
            if feed != self.current_feed:
                feed_cmd = f" F{self._fmt_f(feed)}"
                self.current_feed = feed

            cmd = self._motion_line("G1", seg.end, extra=feed_cmd)
            if cmd:
                lines.append(cmd)
            self.current_pos = seg.end.copy()
            return lines

        # Handle helical interpolation as G2/G3 with Z component
        if seg.motion_type == MotionType.HELIX:
            if self.canned_cycle_active:
                lines.append("G80")
                self.canned_cycle_active = False
                self._cycle_op_id = None
            code = "G3" if seg.arc_ccw else "G2"
            feed = seg.feed or self.current_feed or 500.0
            self.cut_dist += dist
            self.cut_time += (dist / max(feed, 10.0)) * 60.0
            feed_cmd = ""
            if feed != self.current_feed:
                feed_cmd = f" F{self._fmt_f(feed)}"
                self.current_feed = feed

            if seg.arc_center is not None:
                i_off = seg.arc_center[0] - seg.start[0]
                j_off = seg.arc_center[1] - seg.start[1]
                ij_str = f" I{self._fmt(i_off)} J{self._fmt(j_off)}"
            else:
                # Compute I/J from start/end/arc_ccw
                i_off, j_off = self._compute_arc_center_offset(seg.start, seg.end, seg.arc_ccw)
                ij_str = f" I{self._fmt(i_off)} J{self._fmt(j_off)}"

            cmd = self._motion_line(code, seg.end, extra=f"{ij_str}{feed_cmd}")
            if cmd:
                lines.append(cmd)
            self.current_pos = seg.end.copy()
            return lines

        # Handle circular interpolation
        if seg.motion_type in (MotionType.ARC_CW, MotionType.ARC_CCW):
            code = "G3" if seg.motion_type == MotionType.ARC_CCW else "G2"
            feed = seg.feed or self.current_feed or 500.0
            self.cut_dist += dist
            self.cut_time += (dist / max(feed, 10.0)) * 60.0

            feed_cmd = ""
            if feed != self.current_feed:
                feed_cmd = f" F{self._fmt_f(feed)}"
                self.current_feed = feed

            if seg.arc_center is not None:
                i_off = seg.arc_center[0] - seg.start[0]
                j_off = seg.arc_center[1] - seg.start[1]
                ij_str = f" I{self._fmt(i_off)} J{self._fmt(j_off)}"
            else:
                # Compute I/J from start/end points and arc direction
                i_off, j_off = self._compute_arc_center_offset(seg.start, seg.end, seg.arc_ccw)
                ij_str = f" I{self._fmt(i_off)} J{self._fmt(j_off)}"

            cmd = self._motion_line(code, seg.end, extra=f"{ij_str}{feed_cmd}")
            if cmd:
                lines.append(cmd)
            self.current_pos = seg.end.copy()
            return lines

        return lines

    def _motion_line(self, mode: str, target: np.ndarray, extra: str = "") -> Optional[str]:
        parts = []
        if mode != self.current_motion_mode or not self.is_pos_established:
            parts.append(mode)
            self.current_motion_mode = mode

        # Establish complete positioning state on operation start
        if not self.is_pos_established:
            parts.append(self.format_coord("X", target[0]))
            parts.append(self.format_coord("Y", target[1]))
            parts.append(self.format_coord("Z", target[2]))
            self.is_pos_established = True
        else:
            if abs(target[0] - self.current_pos[0]) > 1e-4:
                parts.append(self.format_coord("X", target[0]))
            if abs(target[1] - self.current_pos[1]) > 1e-4:
                parts.append(self.format_coord("Y", target[1]))
            if abs(target[2] - self.current_pos[2]) > 1e-4:
                parts.append(self.format_coord("Z", target[2]))

        if not parts and not extra:
            return None
        if not parts and extra:
            parts.append(mode)

        res = " ".join(parts)
        if extra:
            res += extra
        return res

    def _compute_arc_center_offset(self, start: np.ndarray, end: np.ndarray,
                                    ccw: bool) -> tuple[float, float]:
        """Compute I/J arc center offsets from start/end when arc_center is unknown.

        For a 2-point arc, the center lies on the perpendicular bisector.
        We assume a semicircle (180-degree arc) as the most reasonable default,
        placing the center at the midpoint of the chord offset by radius/2
        perpendicular to the chord in the direction dictated by ccw.
        """
        dx = end[0] - start[0]
        dy = end[1] - start[1]
        chord = math.sqrt(dx * dx + dy * dy)
        if chord < 1e-12:
            return 0.0, 0.0
        # Perpendicular direction (rotated 90 degrees)
        # For CCW: center is to the left of the chord direction
        # For CW: center is to the right
        if ccw:
            perp_x, perp_y = -dy / chord, dx / chord
        else:
            perp_x, perp_y = dy / chord, -dx / chord
        # For a semicircle, radius = chord/2, center is at midpoint + radius * perp
        radius = chord / 2.0
        cx = (start[0] + end[0]) / 2.0 + perp_x * radius
        cy = (start[1] + end[1]) / 2.0 + perp_y * radius
        # I/J are relative to start point
        return cx - start[0], cy - start[1]

    def post_process(self, toolpaths: list[Toolpath], program_name: str = "VEXCAM") -> PostResult:
        """Translate a sequence of Toolpath objects into G-code."""
        self.rapid_dist = 0.0
        self.cut_dist = 0.0
        self.rapid_time = 0.0
        self.cut_time = 0.0
        self.used_tools = []
        self.current_pos = np.array([0.0, 0.0, 0.0])
        self.current_feed = None
        self.current_spindle = None
        self.current_motion_mode = None
        self.spindle_active = False
        self.coolant_active = False
        self.current_tool_id = None
        self.canned_cycle_active = False
        self._cycle_op_id = None
        self._cycle_r_plane = 0.0
        self.is_pos_established = False

        output_lines: list[str] = []
        output_lines.extend(self.header(program_name))

        for tp in toolpaths:
            output_lines.append(f"\n(--- Operation: {tp.operation_id} [{tp.purpose}] Tool: {tp.tool_id} ---)")
            self.is_pos_established = False

            if tp.tool_id and tp.tool_id != self.current_tool_id:
                t_num = 1
                try:
                    t_num = int("".join(filter(str.isdigit, tp.tool_id))) or 1
                except ValueError:
                    t_num = 1
                h_offset = None
                for s in tp.segments:
                    if s.motion_type is MotionType.TOOL_CHANGE and \
                            s.metadata.get("length_offset_h") is not None:
                        h_offset = s.metadata["length_offset_h"]
                        break
                if self.canned_cycle_active:
                    output_lines.append("G80")
                    self.canned_cycle_active = False
                    self._cycle_op_id = None
                output_lines.extend(self.tool_change(tp.tool_id, t_num, h_offset))
                self.is_pos_established = False

            # Operation-level setup / HSM mode hook
            tp_start = self.start_toolpath(tp)
            if tp_start:
                output_lines.extend(tp_start)

            fitted_segments = self._arc_fitting(tp.segments)
            for seg in fitted_segments:
                seg_lines = self.process_segment(seg)
                output_lines.extend(seg_lines)

        output_lines.extend(self.footer())
        full_gcode = "\n".join(output_lines)

        return PostResult(
            gcode=full_gcode,
            line_count=len(output_lines),
            rapid_time_seconds=self.rapid_time,
            cut_time_seconds=self.cut_time,
            total_time_seconds=self.rapid_time + self.cut_time,
            total_rapid_dist_mm=self.rapid_dist,
            total_cut_dist_mm=self.cut_dist,
            tool_changes=self.used_tools,
            work_offset=self.work_offset,
        )

    def _arc_fitting(self, segments: list[MotionSegment]) -> list[MotionSegment]:
        if len(segments) < 3:
            return list(segments)

        result: list[MotionSegment] = []
        i = 0
        while i < len(segments):
            seg = segments[i]
            if seg.motion_type != MotionType.CUT or seg.feed is None:
                result.append(seg)
                i += 1
                continue

            arc_start = i
            pts = [seg.start.copy(), seg.end.copy()]
            j = i + 1
            while j < len(segments):
                next_seg = segments[j]
                if next_seg.motion_type != MotionType.CUT:
                    break
                pts.append(next_seg.end.copy())
                if len(pts) >= 4:
                    fitted, center, ccw = self._fit_arc(pts)
                    if fitted:
                        j += 1
                        continue
                    else:
                        pts.pop()
                        break
                else:
                    j += 1

            if len(pts) >= 4:
                fitted, center, ccw = self._fit_arc(pts)
                if fitted:
                    arc_seg = MotionSegment(
                        motion_type=MotionType.ARC_CCW if ccw else MotionType.ARC_CW,
                        start=pts[0],
                        end=pts[-1],
                        space=seg.space,
                        feed=seg.feed,
                        spindle=seg.spindle,
                        tool_id=seg.tool_id,
                        operation_id=seg.operation_id,
                        feature_id=seg.feature_id,
                        arc_center=center,
                        arc_ccw=ccw,
                    )
                    result.append(arc_seg)
                    i = j
                    continue

            result.append(seg)
            i += 1

        return result

    def _fit_arc(self, points: list[np.ndarray]) -> tuple[bool, Optional[np.ndarray], bool]:
        if len(points) < 3:
            return False, None, False

        p0, p1, p2 = points[0], points[1], points[2]

        a = p1[:2] - p0[:2]
        b = p2[:2] - p0[:2]
        cross = a[0] * b[1] - a[1] * b[0]
        if abs(cross) < 1e-12:
            return False, None, False

        mid_ab = (p0[:2] + p1[:2]) / 2
        mid_bc = (p1[:2] + p2[:2]) / 2

        perp_a = np.array([-a[1], a[0]])
        perp_b = np.array([-b[1], b[0]])

        denom = perp_a[0] * perp_b[1] - perp_a[1] * perp_b[0]
        if abs(denom) < 1e-12:
            return False, None, False

        t = ((mid_bc[0] - mid_ab[0]) * perp_b[1] - (mid_bc[1] - mid_ab[1]) * perp_b[0]) / denom
        center_2d = mid_ab + t * perp_a

        r = np.linalg.norm(p0[:2] - center_2d)
        for p in points:
            dist = abs(np.linalg.norm(p[:2] - center_2d) - r)
            if dist > 0.05:
                return False, None, False

        v0 = p0[:2] - center_2d
        v1 = p1[:2] - center_2d
        cross_z = v0[0] * v1[1] - v0[1] * v1[0]
        ccw = cross_z > 0

        center_3d = np.array([center_2d[0], center_2d[1], p0[2]])
        return True, center_3d, ccw


class GrblPostProcessor(BasePostProcessor):
    """GRBL-compatible post processor. Standard GRBL v1.1 does not support
    canned cycles (G81-G89) or G98/G99. All drilling must use explicit motion."""

    supported_cycles: set[str] = set()  # GRBL has no canned cycle support

    def header(self, program_name: str = "VEXCAM") -> list[str]:
        return [
            f"; Program: {program_name}",
            "; Generated by VexCAM",
            "G90 G94 G17 G21 G40 G49 G80",
            f"{self.work_offset}",
        ]

    def tool_change(self, tool_id: str, tool_num: int = 1,
                    length_offset_h: Optional[int] = None) -> list[str]:
        lines = []
        if self.current_tool_id != tool_id:
            if self.spindle_active:
                lines.append("M5")
                self.spindle_active = False
            # Retract Z before tool change for safety
            if self.is_pos_established:
                lines.append("G0 Z20.0")
            lines.append(f"; Tool change: {tool_id} (T{tool_num})")
            lines.append(f"T{tool_num} M0 (Change to {tool_id})")
            if length_offset_h is not None:
                lines.append(f"; Length offset H{length_offset_h}")
            self.current_tool_id = tool_id
            self.is_pos_established = False
            if tool_id not in self.used_tools:
                self.used_tools.append(tool_id)
        return lines

    def footer(self) -> list[str]:
        lines = []
        if self.canned_cycle_active:
            lines.append("G80")
            self.canned_cycle_active = False
            self._cycle_op_id = None
        if self.coolant_active:
            lines.append("M9")
        if self.spindle_active:
            lines.append("M5")
        lines.append("G0 Z20.0")
        lines.append("G0 X0 Y0")
        lines.append("M2")
        return lines


class FanucPostProcessor(BasePostProcessor):
    """Fanuc 3-axis CNC mill post processor with line numbering and AICC lookahead."""

    def __init__(self, line_increment: int = 10, **kwargs):
        super().__init__(**kwargs)
        self.line_num = line_increment
        self.line_increment = line_increment

    def process_segment(self, seg: MotionSegment) -> list[str]:
        """Override dwell to emit P in milliseconds for Fanuc."""
        if seg.motion_type == MotionType.DWELL:
            # Fanuc G4 expects P in milliseconds (integer)
            p_ms = int(round(seg.dwell_seconds * 1000.0))
            self.cut_time += seg.dwell_seconds
            return [f"G4 P{p_ms}"]
        return super().process_segment(seg)

    def _fmt_cycle_dwell(self, dwell_seconds: float) -> str:
        """Fanuc canned cycle dwell P in milliseconds."""
        p_ms = int(round(dwell_seconds * 1000.0))
        return f"P{p_ms}"

    def header(self, program_name: str = "VEXCAM") -> list[str]:
        lines = [
            "%",
            f"O1001 ({program_name})",
            "(FANUC 3-AXIS MILL POST)",
            "G00 G17 G21 G40 G49 G80 G90",
            f"{self.work_offset}",
        ]
        if self.hsm_enabled:
            lines.append("G05.1 Q1 (AICC Lookahead ON)")
        return lines

    def footer(self) -> list[str]:
        lines = []
        if self.canned_cycle_active:
            lines.append("G80")
            self.canned_cycle_active = False
            self._cycle_op_id = None
        if self.comp_active:
            lines.extend(self.cutter_compensation_off())
            self.comp_active = False
            self.comp_side = None
        if self.coolant_active:
            lines.append("M09")
        if self.spindle_active:
            lines.append("M05")
        if self.hsm_enabled:
            lines.append("G05.1 Q0 (AICC Lookahead OFF)")
        lines.extend([
            "G49 G40",
            "G91 G28 Z0.0",
            "G28 X0.0 Y0.0",
            "M30",
            "%",
        ])
        return lines


class HaasPostProcessor(BasePostProcessor):
    """Haas VF-series CNC mill post processor with G187 smoothing modes."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def start_toolpath(self, tp: Toolpath) -> list[str]:
        if not self.hsm_enabled:
            return []
        mode = tp.metadata.get("hsm_mode") if tp.metadata else None
        if not mode:
            if tp.purpose in ("roughing", "facing", "rest_machining"):
                mode = "roughing"
            elif tp.purpose in ("semi_finishing", "chamfering", "countersinking", "grooving"):
                mode = "medium"
            else:
                mode = "finishing"
        if mode != self.current_hsm_mode:
            self.current_hsm_mode = mode
            p_code = 1 if mode == "roughing" else (2 if mode == "medium" else 3)
            return [f"G187 P{p_code} (Haas High-Speed Smoothing {mode.upper()})"]
        return []

    def process_segment(self, seg: MotionSegment) -> list[str]:
        """Override dwell to emit P in milliseconds for Haas."""
        if seg.motion_type == MotionType.DWELL:
            p_ms = int(round(seg.dwell_seconds * 1000.0))
            self.cut_time += seg.dwell_seconds
            return [f"G4 P{p_ms}"]
        return super().process_segment(seg)

    def _fmt_cycle_dwell(self, dwell_seconds: float) -> str:
        """Haas canned cycle dwell P in milliseconds."""
        p_ms = int(round(dwell_seconds * 1000.0))
        return f"P{p_ms}"

    def header(self, program_name: str = "VEXCAM") -> list[str]:
        return [
            "%",
            f"O01001 ({program_name})",
            "(HAAS CNC MILL)",
            "G00 G17 G21 G40 G49 G80 G90",
            f"{self.work_offset}",
        ]

    def footer(self) -> list[str]:
        lines = []
        if self.canned_cycle_active:
            lines.append("G80")
            self.canned_cycle_active = False
            self._cycle_op_id = None
        if self.comp_active:
            lines.extend(self.cutter_compensation_off())
            self.comp_active = False
            self.comp_side = None
        if self.coolant_active:
            lines.append("M09")
        if self.spindle_active:
            lines.append("M05")
        if self.hsm_enabled and self.current_hsm_mode is not None:
            lines.append("G187 (Restore Haas default smoothing)")
        lines.extend([
            "G49 G40",
            "G53 G00 Z0.0",
            "G53 G00 X0.0 Y0.0",
            "M30",
            "%",
        ])
        return lines


class LinuxCncPostProcessor(BasePostProcessor):
    """LinuxCNC / AXIS post processor (strict RS274/NGC)."""

    def header(self, program_name: str = "VEXCAM") -> list[str]:
        return [
            f"(LinuxCNC Program: {program_name})",
            "G21 (Units in mm)",
            "G90 (Absolute distance mode)",
            "G94 (Units per minute feed rate)",
            "G17 (XY Plane)",
            f"{self.work_offset}",
            "G64 P0.01 Q0.005 (Naive CAM tolerance / path blending)",
        ]

    def footer(self) -> list[str]:
        lines = []
        if self.canned_cycle_active:
            lines.append("G80")
            self.canned_cycle_active = False
            self._cycle_op_id = None
        if self.comp_active:
            lines.extend(self.cutter_compensation_off())
            self.comp_active = False
            self.comp_side = None
        lines.extend([
            "M9",
            "M5",
            "G0 Z25.0",
            "M2",
        ])
        return lines


def get_post_processor(controller: str = "grbl", work_offset: str = "G54") -> BasePostProcessor:
    """Factory helper to obtain a post-processor by controller name."""
    c = controller.lower().strip()
    if "fanuc" in c:
        return FanucPostProcessor(work_offset=work_offset)
    elif "haas" in c:
        return HaasPostProcessor(work_offset=work_offset)
    elif "linux" in c or "ngc" in c:
        return LinuxCncPostProcessor(work_offset=work_offset)
    else:
        return GrblPostProcessor(work_offset=work_offset)
